import re
from bs4 import BeautifulSoup
from urllib.parse import urlparse

def _analyze_crawl_budget(start_url, max_pages=14, timeout=10):
    """Scan homepage + a sample of section pages, bucket discovered URLs by
    query-parameter, classify crawl-budget traps, return robots.txt rules."""
    import html as _html2
    from urllib.parse import urlparse, urljoin, parse_qsl
    if not start_url.startswith('http'):
        start_url = 'https://' + start_url
    pu = urlparse(start_url)
    host = pu.netloc.replace('www.', '')
    base = f"{pu.scheme}://{pu.netloc}"
    ua = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36'}

    try:
        real_urls = _cb_fetch_sitemap_urls(base, ua)
    except Exception:
        real_urls = []
    real_count = len(set(u.split('#')[0] for u in real_urls))

    def _internal(href):
        try:
            p = urlparse(href)
            return (not p.netloc or p.netloc.replace('www.', '') == host) and p.scheme in ('', 'http', 'https')
        except Exception:
            return False

    def grab(url):
        try:
            r = requests.get(url, headers=ua, timeout=timeout)
            if r.status_code != 200 or 'html' not in r.headers.get('Content-Type', '').lower():
                return []
            soup = BeautifulSoup(r.text, 'html.parser')
            out = []
            for a in soup.find_all('a', href=True):
                h = (a.get('href') or '').strip()
                if not h or h.startswith(('#', 'mailto:', 'tel:', 'javascript:')):
                    continue
                absu = urljoin(url, _html2.unescape(h))
                if _internal(absu):
                    out.append(absu)
            return out
        except Exception:
            return []

    fetched = set()
    discovered = []
    home = base + '/'
    discovered.extend(grab(home)); fetched.add(home)
    sections, seen_sec = [], set()
    for u in discovered:
        up = urlparse(u)
        segs = [s for s in up.path.split('/') if s]
        if len(segs) == 1 and not up.query:
            s = base + '/' + segs[0] + '/'
            if s not in seen_sec:
                seen_sec.add(s); sections.append(s)
    for u in sections[:max_pages - 1]:
        if u in fetched:
            continue
        fetched.add(u)
        discovered.extend(grab(u))

    buckets = {}
    for u in discovered:
        q = urlparse(u).query
        if not q:
            continue
        for k, v in parse_qsl(q, keep_blank_values=True):
            nk = _cb_normalise_key(k.lower())
            b = buckets.setdefault(nk, {'urls': set(), 'max_num': 0, 'examples': []})
            b['urls'].add(u)
            if v.isdigit():
                b['max_num'] = max(b['max_num'], int(v))
            if len(b['examples']) < 3:
                b['examples'].append(u)

    VOL_THRESHOLD = 25
    params = []
    for nk, b in buckets.items():
        typ, why = _cb_classify(nk)
        cnt = len(b['urls'])
        recommend = bool(typ) or cnt >= VOL_THRESHOLD
        params.append({
            'key': nk, 'type': typ or 'parameter',
            'why': why or f'{cnt} URLs generated by one parameter — high-volume crawl trap',
            'count': cnt, 'max_num': b['max_num'], 'examples': b['examples'], 'trap': recommend,
        })
    _sev = {'pagination': 5, 'faceting': 4, 'sort': 3, 'tracking': 2, 'session': 2, 'search': 1, 'parameter': 0}
    params.sort(key=lambda p: (p['trap'], _sev.get(p['type'], 0), p['max_num'], p['count']), reverse=True)

    rules, seen = [], set()
    for p in params:
        if not p['trap']:
            continue
        k = p['key']
        if k.endswith('-*'):
            rule = f"Disallow: /*{k[:-1]}"
        elif k.startswith('utm_'):
            rule = "Disallow: /*utm_"
        else:
            rule = f"Disallow: /*{k}="
        if rule not in seen:
            seen.add(rule); rules.append(rule)
    robots_block = ("User-agent: *\n" + "\n".join(rules)) if rules else ''

    return {
        'url': base, 'real_count': real_count, 'pages_scanned': len(fetched),
        'params': params, 'trap_count': sum(1 for p in params if p['trap']),
        'trap_url_estimate': sum(p['count'] for p in params if p['trap']),
        'robots_block': robots_block,
    }


def detect_cms(url, html=None, headers=None):
    """Identify the CMS (and SEO plugin if any) from the HTML + response headers.

    Returns {'cms': key, 'label': str, 'confidence': 'high|medium|low', 'signals': [str]}
    or {'cms': None, ...} if nothing recognisable is found.
    """
    headers = {k.lower(): (v or '') for k, v in (headers or {}).items()}
    html_sample = (html or '')[:80000]  # cap scan to first 80kb — fingerprints live in <head>
    lower = html_sample.lower()
    signals = []
    confidence = 'low'

    def meta_generator():
        m = _re.search(r'<meta[^>]+name=["\']generator["\'][^>]+content=["\']([^"\']+)["\']', html_sample, _re.I)
        return m.group(1) if m else ''

    gen = meta_generator()
    gen_lower = gen.lower()

    # --- High-confidence header/meta matches ---
    if 'x-shopify-stage' in headers or 'x-shopid' in headers or 'cdn.shopify.com' in lower or '/cdn/shop/' in lower:
        signals.append('Shopify CDN / header fingerprint')
        return {'cms': 'shopify', 'label': CMS_PROFILES['shopify']['label'], 'confidence': 'high', 'signals': signals}
    if 'x-wix-request-id' in headers or 'wix.com' in headers.get('x-powered-by', '').lower() or 'wixsite.com' in lower or gen_lower.startswith('wix.com'):
        signals.append('Wix header / generator fingerprint')
        return {'cms': 'wix', 'label': CMS_PROFILES['wix']['label'], 'confidence': 'high', 'signals': signals}
    if 'squarespace' in headers.get('server', '').lower() or 'static1.squarespace.com' in lower or 'squarespace-cdn.com' in lower or gen_lower.startswith('squarespace'):
        signals.append('Squarespace CDN / server fingerprint')
        return {'cms': 'squarespace', 'label': CMS_PROFILES['squarespace']['label'], 'confidence': 'high', 'signals': signals}

    # Webflow
    if 'webflow.com' in lower or _re.search(r'<html[^>]+data-wf-', html_sample) or gen_lower.startswith('webflow'):
        signals.append('Webflow generator / data-wf-* attributes')
        return {'cms': 'webflow', 'label': CMS_PROFILES['webflow']['label'], 'confidence': 'high', 'signals': signals}

    # Kajabi
    if 'kajabi-storefronts-production' in lower or gen_lower.startswith('kajabi'):
        signals.append('Kajabi storefront assets')
        return {'cms': 'kajabi', 'label': CMS_PROFILES['kajabi']['label'], 'confidence': 'high', 'signals': signals}

    # Ghost
    if gen_lower.startswith('ghost') or '/ghost/' in lower or headers.get('x-powered-by', '').lower().startswith('ghost'):
        signals.append('Ghost generator / admin path')
        return {'cms': 'ghost', 'label': CMS_PROFILES['ghost']['label'], 'confidence': 'high', 'signals': signals}

    # HubSpot
    if 'hs-scripts.com' in lower or 'hubspot.net' in lower or 'hubspotusercontent' in lower or gen_lower.startswith('hubspot'):
        signals.append('HubSpot asset CDN')
        return {'cms': 'hubspot', 'label': CMS_PROFILES['hubspot']['label'], 'confidence': 'high', 'signals': signals}

    # Drupal
    if gen_lower.startswith('drupal') or 'x-generator' in headers and 'drupal' in headers['x-generator'].lower() or '/sites/default/files/' in lower:
        signals.append('Drupal generator / asset path')
        return {'cms': 'drupal', 'label': CMS_PROFILES['drupal']['label'], 'confidence': 'high', 'signals': signals}

    # Joomla
    if gen_lower.startswith('joomla'):
        signals.append('Joomla generator meta')
        return {'cms': 'joomla', 'label': CMS_PROFILES['joomla']['label'], 'confidence': 'high', 'signals': signals}

    # --- WordPress detection (+ SEO plugin) ---
    wp_signals = []
    if 'wp-content' in lower or '/wp-includes/' in lower: wp_signals.append('wp-content / wp-includes asset path')
    if '/wp-json/' in lower: wp_signals.append('WordPress REST API link')
    if gen_lower.startswith('wordpress'): wp_signals.append(f'generator: {gen}')
    if headers.get('x-powered-by', '').lower().startswith('wordpress'): wp_signals.append('X-Powered-By: WordPress')
    if wp_signals:
        signals.extend(wp_signals)
        # SEO plugin fingerprints
        if _re.search(r'yoast seo', lower) or 'yoast.com' in lower or _re.search(r'yoast-schema-graph', lower):
            signals.append('Yoast SEO detected')
            return {'cms': 'wordpress_yoast', 'label': CMS_PROFILES['wordpress_yoast']['label'], 'confidence': 'high', 'signals': signals}
        if _re.search(r'rank math', lower) or 'rankmath' in lower:
            signals.append('Rank Math detected')
            return {'cms': 'wordpress_rankmath', 'label': CMS_PROFILES['wordpress_rankmath']['label'], 'confidence': 'high', 'signals': signals}
        return {'cms': 'wordpress', 'label': CMS_PROFILES['wordpress']['label'], 'confidence': 'high', 'signals': signals}

    return {'cms': None, 'label': 'Unknown / custom', 'confidence': 'low', 'signals': []}


def _detect_js_platform(html):
    """Cheap signature check for JS-rendered platforms. Returns a human-
    readable platform name or None.

    Used to tell the user "this site needs Render JS" instead of firing a
    misleading "No analytics detected" issue when the crawler saw only the
    unhydrated HTML shell.
    """
    if not html:
        return None
    sample = html[:200_000]  # enough for <head> + top of <body>
    checks = [
        ('Wix',         [r'static\.parastorage\.com', r'wix\.com/thunderbolt', r'wixCIDX', r'<html[^>]*wix']),
        ('Shopify',     [r'cdn\.shopify\.com', r'Shopify\.shop', r'shopify-features']),
        ('Squarespace', [r'static1\.squarespace\.com', r'squarespace-cdn\.com', r'Squarespace\.Constants']),
        ('Webflow',     [r'uploads-ssl\.webflow\.com', r'data-wf-page', r'webflow\.js']),
        ('Next.js',     [r'id="__next"', r'__NEXT_DATA__']),
        ('Nuxt',        [r'id="__nuxt"', r'window\.__NUXT__']),
        ('Gatsby',      [r'id="___gatsby"']),
        ('React SPA',   [r'<div[^>]+id="root"[^>]*></div>\s*<script']),
        ('Vue SPA',     [r'<div[^>]+id="app"[^>]*></div>\s*<script']),
    ]
    import re as _re_local
    for name, patterns in checks:
        for pat in patterns:
            if _re_local.search(pat, sample, _re_local.I):
                return name
    return None


def _is_third_party_widget_image(abs_src):
    """Return True for images injected by third-party widgets/trackers.

    The crawler can see these but the site owner cannot meaningfully add alt
    text — reCAPTCHA logos, analytics 1×1 beacons, chat-widget assets, etc.
    Filtering them out keeps the 'imgs missing alt' view actionable.
    """
    if not abs_src:
        return False
    try:
        from urllib.parse import urlparse as _up
        host = (_up(abs_src).hostname or '').lower()
    except Exception:
        host = ''
    if host:
        for h in _THIRD_PARTY_IMG_HOSTS:
            if host == h or host.endswith('.' + h):
                return True
    if _THIRD_PARTY_IMG_FILE_RE.search(abs_src):
        return True
    return False


def _filename_looks_decorative(src):
    """Heuristic: does this image filename look like a decorative shape /
    icon / pattern export rather than a content photo / screenshot / logo?

    Decorative (True):  Layer-1.svg, Group-83.png, Mask-Group-2.png,
                        quotation.png, pattern-dots.svg, hero-bg.jpg,
                        icon-arrow.svg, divider.png
    Content (False):    hero-team.jpg, screenshot-2026-04-12.png,
                        logo-white.png, unrecognizable-man-working.jpg

    Used to split <img alt=""> into 'genuinely decorative' (info) and
    'likely content with forgotten alt' (surfaced as an issue).
    """
    if not src:
        return True
    try:
        from urllib.parse import urlparse as _up
        path = _up(src).path or src
    except Exception:
        path = src
    fname = path.rsplit('/', 1)[-1]
    if not fname:
        return True
    fname = _re.sub(r'\.(svg|png|jpe?g|gif|webp|avif|ico|bmp)$', '', fname, flags=_re.I)
    fname = _re.sub(r'[-_]\d{2,4}x\d{2,4}$', '', fname)
    fname = _re.sub(r'@\d+x$', '', fname)
    fname = _re.sub(r'[-_]scaled$', '', fname, flags=_re.I)
    return bool(_DECORATIVE_FILENAME_RE.search(fname))


def _parse_no_js_subset(html, base_url):
    """Parse a subset of SEO-critical fields from raw HTML — used for the
    JS-vs-non-JS comparison so we can show what content is missing when JS
    isn't executed. Same parsers/idioms as the main pass in `_crawl_page`,
    just trimmed to the fields we diff against. Kept self-contained on
    purpose — no shared state with the main crawl pass.
    """
    from urllib.parse import urlparse, urljoin
    out = {
        'title': '', 'meta_description': '', 'h1': '', 'h1_count': 0,
        'word_count': 0, 'schema_types': [],
        'internal_links_count': 0, 'external_links_count': 0,
        'images_count': 0, 'images_no_alt': 0,
    }
    try:
        soup = BeautifulSoup(html or '', 'html.parser')
        t = soup.find('title')
        out['title'] = t.get_text(strip=True) if t else ''
        m = soup.find('meta', attrs={'name': 'description'})
        out['meta_description'] = m.get('content', '') if m else ''
        import re as _re_h
        def _clean_h(tag):
            txt = ' '.join(tag.get_text(' ', strip=True).split())
            return _re_h.sub(r'\s+([,.;:!?\)\]])', r'\1', txt)
        h1s = [_clean_h(h) for h in soup.find_all('h1')]
        h1s = [h for h in h1s if h]
        out['h1'] = h1s[0] if h1s else ''
        out['h1_count'] = len(h1s)
        for s in soup(['script', 'style', 'noscript']):
            s.decompose()
        body_text = ' '.join(soup.get_text(separator=' ', strip=True).split())
        out['word_count'] = len(body_text.split()) if body_text else 0
        types = []
        def _push(v):
            if isinstance(v, list):
                for x in v:
                    if isinstance(x, str): types.append(x)
            elif isinstance(v, str):
                types.append(v)
        for sc in soup.find_all('script', attrs={'type': 'application/ld+json'}):
            try:
                ld = json.loads(sc.string or '')
                if isinstance(ld, dict):
                    if '@type' in ld: _push(ld['@type'])
                    if '@graph' in ld:
                        for it in ld['@graph']:
                            if isinstance(it, dict) and '@type' in it:
                                _push(it['@type'])
                elif isinstance(ld, list):
                    for it in ld:
                        if isinstance(it, dict) and '@type' in it:
                            _push(it['@type'])
            except Exception:
                pass
        out['schema_types'] = types
        try:
            host = (urlparse(base_url).netloc or '').lower().replace('www.', '')
        except Exception:
            host = ''
        for a in soup.find_all('a', href=True):
            href = a.get('href', '').strip()
            if not href or href.startswith(('#', 'javascript:', 'mailto:', 'tel:')):
                continue
            try:
                abs_url = urljoin(base_url, href)
                link_host = (urlparse(abs_url).netloc or '').lower().replace('www.', '')
            except Exception:
                continue
            if link_host == host or not link_host:
                out['internal_links_count'] += 1
            else:
                out['external_links_count'] += 1
        imgs = soup.find_all('img')
        out['images_count'] = len(imgs)
        out['images_no_alt'] = sum(1 for i in imgs if not (i.get('alt') or '').strip())
    except Exception:
        pass
    return out


def _compute_js_diff(js, nojs):
    """Compare rendered (post-JS) fields against pre-JS subset and classify
    severity.
    Severity ladder: critical (title/meta/schema), high (h1/word_count),
    medium (links/images), none (page is server-rendered correctly).
    """
    fields_differ = []
    sev = 'none'
    rendered_title = (js.get('title') or '').strip()
    nojs_title = (nojs.get('title') or '').strip()
    if rendered_title != nojs_title:
        fields_differ.append('title'); sev = 'critical'
    rendered_meta = (js.get('meta_description') or '').strip()
    nojs_meta = (nojs.get('meta_description') or '').strip()
    if rendered_meta != nojs_meta:
        fields_differ.append('meta_description'); sev = 'critical'
    js_schema = sorted(set(js.get('schema_types') or []))
    nojs_schema = sorted(set(nojs.get('schema_types') or []))
    if js_schema != nojs_schema:
        fields_differ.append('schema_types'); sev = 'critical'
    rendered_h1 = (js.get('h1') or '').strip()
    nojs_h1 = (nojs.get('h1') or '').strip()
    if rendered_h1 != nojs_h1:
        fields_differ.append('h1')
        if sev != 'critical': sev = 'high'
    js_wc = js.get('word_count') or 0
    nojs_wc = nojs.get('word_count') or 0
    if js_wc > 0 and abs(js_wc - nojs_wc) / max(js_wc, 1) > 0.25:
        fields_differ.append('word_count')
        if sev != 'critical': sev = 'high'
    js_il = js.get('internal_links') or 0
    nojs_il = nojs.get('internal_links_count') or 0
    if js_il > 0 and abs(js_il - nojs_il) / max(js_il, 1) > 0.25:
        fields_differ.append('internal_links')
        if sev not in ('critical', 'high'): sev = 'medium'
    js_el = js.get('external_links') or 0
    nojs_el = nojs.get('external_links_count') or 0
    if js_el > 0 and abs(js_el - nojs_el) / max(js_el, 1) > 0.25:
        fields_differ.append('external_links')
        if sev not in ('critical', 'high'): sev = 'medium'
    js_imgs = js.get('images_total') or 0
    nojs_imgs = nojs.get('images_count') or 0
    if js_imgs > 0 and abs(js_imgs - nojs_imgs) / max(js_imgs, 1) > 0.10:
        fields_differ.append('images_total')
        if sev not in ('critical', 'high'): sev = 'medium'
    if (js.get('images_no_alt') or 0) != (nojs.get('images_no_alt') or 0):
        fields_differ.append('images_no_alt')
        if sev not in ('critical', 'high'): sev = 'medium'
    return {'severity': sev, 'fields': fields_differ}


def _detect_waf_block(resp):
    """Sniff a 403/429/503 response for WAF block-page markers.
    Returns 'wordfence' / 'cloudflare' / 'sucuri' / 'siteground' / None.
    Retrying these against the same IP just escalates the block — the caller
    should bail out of retries and let the host-pause kick in for ~5 minutes."""
    if resp is None: return None
    if resp.status_code not in (403, 429, 503): return None
    try:
        body_head = (resp.text or '')[:4000].lower()
    except Exception:
        return None
    if 'wordfence' in body_head or 'generated by wordfence' in body_head:
        return 'wordfence'
    if 'attention required' in body_head and 'cloudflare' in body_head:
        return 'cloudflare'
    if 'sucuri' in body_head and ('website firewall' in body_head or 'access denied' in body_head):
        return 'sucuri'
    if 'siteground' in body_head and ('blocked' in body_head or 'security' in body_head):
        return 'siteground'
    return None


def _is_challenge_response(resp):
    """True if a 403/503 is a solvable bot interstitial (vs a hard WAF block)."""
    if resp is None:
        return False
    try:
        from challenge_browser import is_challenge_response
        return is_challenge_response(resp.status_code, dict(resp.headers), resp.text)
    except Exception:
        return False


def _probe_url_traps(base, results, session):
    """Post-crawl soft-404 / infinite-URL-trap probe (max 2 extra requests).

    Probe A (root): GET /<random-token>/ — a 200 means the server never 404s,
    so every mistyped or bot-invented URL becomes an indexable duplicate.
    Probe B (nested): GET <real crawled page>/<random-token>/ — a 200 here is
    worse: the served page's relative links resolve one level deeper, minting
    an INFINITE URL space. Scrapers/bots walk it forever, which bloats the
    index, wastes crawl budget, and can burn unlimited bandwidth on a
    transfer-capped host (509 Bandwidth Limit Exceeded).
    Redirects and 4xx/5xx on the probes = healthy. Never raises.
    """
    import uuid as _uuid
    token = f"url-trap-probe-{_uuid.uuid4().hex[:10]}"
    out = {'checked': True, 'soft_404': False, 'nested_trap': False, 'probes': []}
    # Nested-probe parent: prefer a single-segment page (cleanest signal),
    # else any non-homepage 200 page — the trap behaviour is the same.
    parent = fallback = None
    from urllib.parse import urlparse as _up
    for r in results:
        u = r.get('url') or ''
        if r.get('status_code') == 200 and not r.get('redirect_url') and u:
            segs = [s for s in _up(u).path.split('/') if s]
            if len(segs) == 1:
                parent = r
                break
            if segs and fallback is None:
                fallback = r
    parent = parent or fallback
    probes = [('root', f"{base.rstrip('/')}/{token}/", None)]
    if parent:
        probes.append(('nested', f"{parent['url'].rstrip('/')}/{token}/", parent))
    for kind, purl, par in probes:
        try:
            resp = session.get(purl, timeout=12, allow_redirects=False)
            entry = {'kind': kind, 'url': purl, 'status': resp.status_code}
            if resp.status_code == 200:
                out['soft_404' if kind == 'root' else 'nested_trap'] = True
                m = re.search(r'<title[^>]*>(.*?)</title>', resp.text[:30000], re.I | re.S)
                title = (m.group(1).strip() if m else '')[:200]
                if title:
                    entry['title'] = title
                if par and title and title == (par.get('title') or '').strip():
                    entry['serves'] = 'same content as ' + par['url']
            out['probes'].append(entry)
        except Exception as e:
            out['probes'].append({'kind': kind, 'url': purl, 'error': str(e)[:120]})
    return out


